Beta_Params:
  b_TT: 0.002777777777777778
  b_disc: 0
  b_price: 1
  b_rel: 0.002777777777777778
  b_risk: 0.1
Connection_Edge_Speed:
  bs: 4.166666666666667
  pv: 2.2347222222222225
  zip: 2.2347222222222225
Conversion_Factors:
  meters_in_mile: 1609
  miles_in_km: 0.621371
Discomfort_Params:
  alight: 0
  board: 0
  bs: 2.432835820895522
  park: 1.0
  pb: 2.432835820895522
  pt: 1.6567164179104479
  pv: 1.0
  sc: 2.432835820895522
  t: 1.0
  t_wait: 0
  w: 2.134328358208955
  z: 1.0
Geography:
  buffer: 0.2
  neighborhoods:
  - Central Oakland
  - Squirrel Hill South
  - Squirrel Hill North
  - North Oakland
  - Larimer
  - Point Breeze
  - Shadyside
  - East Liberty
Price_Params:
  alight:
    fixed: 0
    ppmile: 0
    ppmin: 0
  board:
    fixed: 2.75
    ppmile: 0
    ppmin: 0
  bs:
    fixed: 0
    ppmile: 0
    ppmin: 0.125
  park:
    fixed: 27
    ppmile: 0
    ppmin: 0
  pb:
    fixed: 0
    ppmile: 0
    ppmin: 0
  pt:
    fixed: 0
    ppmile: 0
    ppmin: 0
  pv:
    fixed: 0
    ppmile: 0.2
    ppmin: 0
  rt:
    fixed: 0
    ppmile: 0
    ppmin: 0
  sc:
    fixed: 0
    ppmile: 0
    ppmin: 0.39
  sc_tx:
    fixed: 1
    ppmile: 0
    ppmin: 0
  t:
    fixed: 0
    ppmile: 1.08
    ppmin: 0.18
  t_wait:
    fixed: 7.57
    ppmile: 0
    ppmin: 0
  w:
    fixed: 0
    ppmile: 0
    ppmin: 0
  z:
    est_num_trips: 4
    fixed: 0
    fixed_per_month: 9
    ppmile: 0
    ppmin: 0.18333333333333332
Reliability_Params:
  board: 2
  t_wait: 2
Risk_Crash_Idx:
  alight: 0.19
  board: 0.19
  bs: 1.81
  park: 1
  pb: 1.81
  pt: 0.19
  pv: 1
  sc: 1.81
  t: 1
  t_wait: 0
  w: 0.28
  z: 1
Scoot_Data_Generation:
  num_days_of_data: 30
  num_obs: 1000.0
Speed_Params:
  TNC:
    wait_time: 7
  bike: 4.027777777777778
  scoot: 2.78
  walk: 1.3
Supernetwork:
  W_od: 0.59
  W_tx: 0.5
  dst:
  - -79.95137478282426
  - 40.43878091188718
  modes_included:
  - bs
  - z
  - sc
  - t
  - pt
  num_park_hours: 2
  org:
  - -79.91101702988759
  - 40.4642694061984
Time_Intervals:
  interval_spacing: 10
  len_period: 3600
  time_end: 9
  time_start: 7
