Active_Mode_Parameters:
  active_modes:
  - w
  - pb
  - bs
  - sc
  discomf_weight_bike: 0.3
  discomf_weight_scoot_walk: 0.1
  nonactive_modes:
  - pv
  - pt
  - t
  - z
  rel_weight_active: 1
  rel_weight_nonactive: 1.5
Beta_Params:
  b_TT: 0.16666666666666666
  b_disc_weight: 0.5
  b_price: 1
  b_rel_weight: 0.75
  b_risk_weight: 1
Conversion_Factors:
  meters_in_mile: 1609
  miles_in_km: 0.621371
Geography:
  neighborhoods:
  - Hazelwood
  - Glen Hazel
  - Greenfield
  - Squirrel Hill South
  - Squirrel Hill North
Price_Params:
  PT_price: 2.75
  TNC_fix_price: 3.1100000000000003
  TNC_minfare_buffer: 2.08
  TNC_ppmile: 0.92
  TNC_ppmin: 0.34
  bs_ppmin: 0.06666666666666667
  pb_ppmin: 0
  pv_ppmile: 0.2
  scoot_ppmin: 0.39
  zip_est_num_trips: 4
  zip_fixed_ppmonth: 9
  zip_ppmin: 0.18333333333333332
Risk_Parameters:
  crash_weight: 5
  risk_weight_active: 1.2
Speed_Params:
  bike_speed: 4.166666666666667
  parking_speed: 2.2347222222222225
  scoot_speed: 4.166666666666667
  walk_speed: 1.3
Time_Intervals:
  interval_spacing: 10
  len_period: 120
  time_end: 9
  time_start: 7
