Beta_Params:
  b_TT: 0.16666666666666666
  b_disc: 0.5
  b_price: 1
  b_rel: 0.75
  b_risk: 1
Connection_Edge_Speed:
  bike: 4.166666666666667
  drive: 2.2347222222222225
Conversion_Factors:
  meters_in_mile: 1609
  miles_in_km: 0.621371
Discomfort_Params:
  PT_traversal: 0
  PT_wait: 0
  TNC: 0
  bike: 0.3
  bs: 0.3
  drive: 0
  pb: 0.3
  pv: 0
  scoot: 0.1
  walk: 0.1
  zip: 0
Geography:
  neighborhoods:
  - Hazelwood
  - Glen Hazel
  - Greenfield
  - Squirrel Hill South
  - Squirrel Hill North
Price_Params:
  PT:
    fixed: 2.75
  TNC:
    fixed: 3.1100000000000003
    minfare_buffer: 2.08
    ppmile: 0.92
    ppmin: 0.34
  bs:
    ppmin: 0.06666666666666667
  pb:
    ppmin: 0
  pv:
    ppmile: 0.2
    ppmin: 0
  scoot:
    fixed: 1
    ppmin: 0.39
  walk:
    ppmin: 0
  zip:
    est_num_trips: 4
    fixed_per_month: 9
    ppmin: 0.18333333333333332
Reliability_Params:
  PT_traversal: 1.5
  PT_wait: 2
  TNC_wait: 2
  bike: 1
  drive: 1.5
  scoot: 1
  walk: 1
Risk_Parameters:
  PT_traversal: 1
  PT_wait: 0.5
  crash_weight: 5
  risk_weight_active: 1.2
Scoot_Data_Generation:
  num_days_of_data: 30
  num_obs: 100
Speed_Params:
  TNC:
    wait_time: 7
  bike: 4.166666666666667
  scoot: 4.166666666666667
  walk: 1.3
Supernetwork:
  W_od: 1.0
  W_tx: 0.5
  modes_included:
  - bs
  - z
  - sc
  - t
  - pt
Time_Intervals:
  interval_spacing: 10
  len_period: 120
  time_end: 9
  time_start: 7
