Beta_Params:
  b_TT: 0.002777777777777778
  b_disc: 0
  b_price: 1
  b_rel: 0.002777777777777778
  b_risk: 0.1
Connection_Edge_Speed:
  bs: 4.166666666666667
  pv: 2.2347222222222225
  zip: 2.2347222222222225
Conversion_Factors:
  meters_in_mile: 1609
  miles_in_km: 0.621371
Discomfort_Params:
  PT_traversal: 1.1
  PT_wait: 1.1
  TNC: 1
  bs: 1.3
  pb: 1.3
  pv: 1
  scoot: 1.1
  walk: 1.1
  zip: 1
Geography:
  neighborhoods:
  - Hazelwood
  - Glen Hazel
  - Greenfield
  - Squirrel Hill South
  - Squirrel Hill North
Price_Params:
  PT:
    fixed: 2.75
  TNC:
    fixed: 6.26
    minfare_buffer: 2.08
    ppmile: 1.08
    ppmin: 0.18
  bs:
    ppmin: 0.125
  pb:
    ppmin: 0
  pv:
    ppmile: 0.2
    ppmin: 0
  scoot:
    fixed: 1
    ppmin: 0.39
  walk:
    ppmin: 0
  zip:
    est_num_trips: 4
    fixed_per_month: 9
    ppmin: 0.18333333333333332
Reliability_Params:
  PT_traversal: 1.5
  PT_wait: 2
  TNC: 1.5
  TNC_wait: 2
  bike: 1
  bs: 1
  drive: 1.5
  pb: 1
  pv: 1.5
  scoot: 1
  walk: 1
  zip: 1.5
Risk_Parameters:
  PT_traversal: 1
  PT_wait: 1
  TNC: 1
  bs: 1.1
  crash_weight: 5
  pb: 1.1
  pv: 1
  scoot: 1.1
  walk: 1.05
  zip: 1
Scoot_Data_Generation:
  num_days_of_data: 30
  num_obs: 500
Speed_Params:
  TNC:
    wait_time: 7
  bike: 4.166666666666667
  scoot: 4.166666666666667
  walk: 1.3
Supernetwork:
  W_od: 0.75
  W_tx: 0.5
  dst:
  - -79.91944888168011
  - 40.45228774674678
  modes_included:
  - bs
  - z
  - sc
  - t
  - pt
  org:
  - -79.94868171046522
  - 40.416379503934145
Time_Intervals:
  interval_spacing: 20
  len_period: 3600
  time_end: 9
  time_start: 7
